services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/var/www
      - /var/www/vendor/
    environment:
      - DB_HOST=mariadb
      - DB_NAME=my_database
      - DB_USER=root
      - DB_PASS=secret
    networks:
      - app-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
